### PR TITLE
Prompt log

### PR DESCRIPTION
**Pull request by shargon**
```
log on
log off
```

Enable log proxy by Console output

image

### CODE REVIEW

**Review by osmirnov — CHANGES_REQUESTED** [review]
What a brutal solution for dynamic logging 😆
1. It breaks abstraction and targets NLog specifically.
2. With this fix we will have Russian doll of loggers: LoggerAdapter -> LoggerProxy -> NLogger
3. It ignores all Console specific setup in configuration (for example, you cannot setup level Info and ColoredConsole as a target)

Before we will continue reviewing this, @shargon have you investigated [this solution](https://stackoverflow.com/a/16427863/321081)? Basically, the idea is to have Console target in configuration with the highest level and lower that when we need to see logging on a certain level.

**Comment by shargon** [comment]
But if the log write directly to console, you can't have control, and could write in the middle of your input. We need a event, maybe not like this, but we need the control

**Comment by osmirnov** [comment]
I see. Then proposed solution won't help. However, correct me if I wrong, now any Log call will wait until mutex releasing, right?

**Comment by shargon** [comment]
We need to improve this solution, maybe is better to append the logs to one queue and dump where the prompt is free, but i want to do this very practical, and if the log is append when arrive, is very cahotic

**Comment by osmirnov** [comment]
I understand where you're coming from. However, if every thread waits for this mutex it means we will kill all parallel work and Log will be a bottleneck when is enabled. How about to read from log files?

**Comment by osmirnov** [comment]
I will close it because, by this change, all threads will wait for the single resource (mutex) and the performance will suffer drastically. It is better not to have such a functionality in the prompt and to read logs from files rather than process fewer operations on nodes.

**Comment by shargon** [comment]
I will solve this issue, but i think that we need this feature, is very useful on neo python, so give me time for fix this

**Comment by osmirnov** [comment]
I am not against this feature but rather against the implementation. Please take your time to fix issues I've mentioned.

**Comment by shargon** [comment]
@osmirnov Do you think that is better create a `ILogFactoryExtended` interface with the event? and inject this interface (for prevent this)

```csharp
if (loggerFactory is NLogLoggerFactory nlog)
            {
                nlog.OnLog += Log_OnLog;
            }
```

**Review by osmirnov — COMMENTED** [review]
Yes, I think:
1. It is much better than before. There is a chance that log generation speed won't allow entering any commands in the console but let's see.
2. It is better to inherit from ILoggerFactory, extend with the event, register both in DI container, inject what is required. As an extra benefit, It will make it testable.
3. LoggerProxy and LoggerAdapter can be merged to avoid multiple levels of the logging extension.
Thanks for your effort on this.

**Comment by shargon** [comment]
Take another look @osmirnov :)

**Comment by osmirnov** [comment]
Ok, this is much better. Now threads will wait on lockObject in WriteLine methods but you already invested enough time in this 😉 Let's keep an eye on it and add that to our todo list for optimizations.

**Review by osmirnov — APPROVED** [review]

**Pull request merged**
