### PR TITLE
Extract cryptography from NeoSharp.Core

### PR DESCRIPTION
**Pull request by aboimpinto**
In order to make NeoSharp modular and the NeoSharp.Core less dependent on external libs

* Extract the Cryptography BouncyCastleCrypto dependency from NeoSharp.Core
* Rename abstract class ICrypto to Crypto
* Rename some private fields according with the coding rules (boy scout rule)
* Move tests of NeoSharp.Cryptography to their own test project

Still non depended on external libs classes in the Cryptography folder in NeoSharp.Core like BloomFilter, ECPoint, Helper, MerkleTree, MerkleTreeNode and ProtectedMemoryContext that I would like to know if should be moved or not?

**Why this objects should be move his own assembly?**
- In order to be reused this features in another projects as NEO-GUI-WPF without have to reference the NeoSharp.Core
- To remove the height of dependencies on the NeoSharp.Core

### CODE REVIEW

**Comment by osmirnov** [comment]
What's the fear to reference NeoSharp.Core assembly? I'd like to refer to the article [Project anti-pattern: Many projects in a Visual Studio Solution File](https://lostechies.com/chadmyers/2008/07/16/project-anti-pattern-many-projects-in-a-visual-studio-solution-file/)

**Comment by aboimpinto** [comment]
Agree that we don't need to have too many assemblies. We gonna need to find a balance on that. 
In the PR i justify the reason. Other projects like the NEO-GUI-WPF need to reference the CORE to be able to have access to Cryptography or types and that make no sense.

This projects don't need to have access to the BynarySerializers, Logging or even Server. This is not only unnecessary but a huge unnecessary memory consuming. 

No one is promoting creating 100 project assemblies but the necessary.

**Comment by aboimpinto** [comment]
Regarding having less assemblies, I would like to point that if it is so bad been pointed, Windows and Visual Studio would be one giant assembly and they aren't, why? Simple, because when other components need to make a reference they don't need to reference this giant assembly but a smaller and more specific.

**Comment by shargon** [comment]
Crypto projects require Types?

**Comment by osmirnov** [comment]
Addressing concerns:
1. *Other projects like the NEO-GUI-WPF need to reference the CORE to be able to have access to Cryptography or types and that make no sense*
Having the access and actually use it without a need are two different things. As I said many times before protecting from developers by introducing physical boundaries is inefficient.
2. *This is not only unnecessary but a huge unnecessary memory consuming.*
I've checked compiled in debug mode NeoSharp.Core. It weights 198KB. It means being loaded it will take approximately this much of memory. I've also checked NeoSharp.BinarySerialization assembly to play role NeoSharp.Cryptography. The size is 22KB. I admit there is a difference but I would not say about **huge** memory consumption.
3. *I would like to point that if it is so bad been pointed, Windows and Visual Studio would be one giant assembly and they aren't, why?*
I feel sarcasm here but I will answer. These applications have many dependent libraries because those parts of software are intended being shipped or versioned independently of each other. I don't need to issue new Windows if I want to patch DirectX. For us, the question is "Could we ship a new version of NeoSharp.Cryptography without shipping NeoSharp.Core? Theoretically, yes. Is it possible to happen in practice? Unlikely. Do we want to manage all these versions? Definitely, no." Now the same exercise for NeoSharp.Types and the answer will be more straightforward: we absolutely cannot release NeoSharp.Types without releasing the rest. 

I will not mark this PR as required changes but my opinion it will bring more harm than usefulness. I ask other members @shargon @gubanotorious @AshRolls to voice their opinions.

**Comment by gubanotorious** [comment]
Changes like this will require consensus from the group and discussion prior to a pull request.  I will be working on a process that contributors will need to follow to propose architectural or refactoring changes prior to implementation and PR.  

At this point I don't see value in this change, and if we do decide to extract the core to multiple assemblies, that will be discussed and decided after we achieve the first use case milestone. 

I don't want to merge this pull request at this point unless it is blatantly blocking progress towards the milestone goal, and if that is the case, we need to specifically understand why.

I think we should revisit this at another time, I don't see this as a proper focus of the groups time right now.

**Comment by shargon** [comment]
I think that we only need to separate Types, because is could be imported as nuget package for plugins or other things

Core -> Nuget [Types and VM together]
|
Nuget [Types and VM together] 
|
HyperVM

**Comment by aboimpinto** [comment]
@osmirnov, you should import the NEO nuget package into a project to understand what that others are talking about ...

I agree with @shargon, most of this extractions from the Neo.Core can be and should be NuGet packaged to be imported in other projects if necessary.

**Pull request closed without merging**
