### PR TITLE
Create tests for the BlockPool class

### PR DESCRIPTION
**Pull request by aboimpinto**
as described

### CODE REVIEW

**Comment by osmirnov** [comment]
@aboimpinto, are you sure you have committed everything? I see a single empty file.

**Review by shargon — CHANGES_REQUESTED** [review]
A lot of beers ? :P

**Comment by aboimpinto** [comment]
HAHAHAHAH
nooo was just the file structure ... the rest will came

**Comment by aboimpinto** [comment]
I try to implement the UpdateHash in the several Signed<object> classes and I would like to know your opinion regarding the BlockHeader. We don't heve Transactions or TransactionHashes ... how we calculate the MerkleRoot?

**Review by osmirnov — COMMENTED** [review]
1. Please do rebase and create a feature branch from your dev to avoid long commit history
2. Please drop Unsigned preffix. Usually, it is not DeserializedObject and SerializedObject or UnvalidatedObject and ValidatedObject but rather Object and SerializedObject and Object and ValidatedObject. Do you know what I mean?
3. This is a great step forward but the code is still lacking a standalone class for checksum calculation/verification. I am sure you are well aware how hard to test logic in the constructor ;) In my initial idea, I referred to some kind of stateless converter that accepts a block and produces a signed block. It is a way easier to test/to mock
4. Private setter for arrays is good but the code still can replace an element by index. Would it better use IReadOnly*?
5. We need to pay extra attention to how we save signed entities in a db and restore them. All readonly protection should not interfere with the persistence. Could you prove it works?

**Comment by aboimpinto** [comment]
tkx for the feedback ...
I know still a lot work to be done and this is far away to be finished ... 
I will create a FeatureBranch for this ... this got way to big ...

Regarding your feedback .. I agree with them all .. For readability reason I will keep the Unsigned and Signed. This will be dropped later.
I like the readability and have the prefix could look too much but show the users of the code the real intention of it.
I will made the change later.

When I was looking for the way to create an interface and have a Mutable and Immutable implementation I came across with this idea of the IReadOnly interface for collections. I didn't want to use because would look strange in the class, some properties with the type and others with this IReadOnly<collection> ... doesn't feel right. Why we cannot use the ReadOnlyCollection? It's a .NET type made just for this and if Microsoft improve the performance on this collection we will get it for free (the performance is already the same as array).

Didn't reach yet the persistence part and I know will be a problem because we gonna need to set the properties. The way I will solved is have a overload in the constructor of the SignedBlock (for exemple) where receive the SignedBlock instead of the UnsignedBlock. With this we can have the Signed<object> be constructed using a Signed or Unsigned object.

**Comment by osmirnov** [comment]
Regards to IReadOnly* I meant to use appropriate IReadOnlyCollection, IReadOnlyList or IReadOnlyDictionary. I did not mean to implement some IReadOnly interface. Sorry, for the confusion it could bring up.

**Review by shargon — APPROVED** [review]

**Comment by gubanotorious** [comment]
Please resolve tests so we can merge this in..

**Comment by aboimpinto** [comment]
Sign logic removed from the model objects and added to the <object>OperationsManager classes that will be responsible for creating the Hash and for Verification.

The method verify wasn't implemented.

**Pull request merged**
