### PR TITLE
Check witness on pubkey

### PR DESCRIPTION
**Pull request by osmirnov**

### CODE REVIEW

**Comment by shargon** [comment]
I think that the problem is that the process of serialize a Transaction was delegated to other class, right?

**Comment by osmirnov** [comment]
I would not say this is a problem but it impacts our code design a lot. I see benefits keeping Transaction class free from serizalization logic.

**Comment by shargon** [comment]
Maybe is better to set the message in binary format

**Comment by osmirnov** [comment]
It was before in binary format. In contrast to original NEO project our Transaction class is not able to be restored from byte array when it is casted to InvocationTransaction. This is the reason why we have two methods in MessageProvider class.

**Review by shargon — APPROVED** [review]

**Pull request merged**
