### PR TITLE
Unify Binary reader/writer

### PR DESCRIPTION
**Pull request by shargon**

### CODE REVIEW

**Comment by aboimpinto** [comment]
why not called BinaryHandler or something like that? Just calling BinarySelializer can miss lead the intent of the class.

**Comment by shargon** [comment]
BinaryHandler ... is not a handler... is a serializer.... find another name @aboimpinto  :P

**Comment by aboimpinto** [comment]
well... it's a serializer and deserializer ... mean .. it's handling serialization and deserialization ... right?

**Comment by aboimpinto** [comment]
for me it's ok ... just point this out that the name could miss lead ...

**Review by aboimpinto — APPROVED** [review]

**Pull request merged**
