### PR TITLE
Pool

### PR DESCRIPTION
**Pull request by shargon**
image

- Fix Travis StackOverflow

### CODE REVIEW

**Comment by shargon** [comment]
Is working in local :(

**Comment by gubanotorious** [comment]
Is this an issue with Travis builds being broken again?

**Comment by shargon** [comment]
yes, you can merge, is working ...

**Comment by shargon** [comment]
travis hates me

**Comment by shargon** [comment]
image

now all is working for me ...

**Comment by gubanotorious** [comment]
Travis is still an issue?

**Pull request merged**
