### PR TITLE
Rename ICrypto to Crypto and increase test coverage on Server

### PR DESCRIPTION
**Pull request by aboimpinto**
Rename abstract class ICrypto to Crypto. I'm sure this was once an interface but it's not anymore, therefore should not carry the prefix "I" that identify the interfaces.

### CODE REVIEW

**Comment by osmirnov** [comment]
We will merge after PR #228

**Comment by aboimpinto** [comment]
I will resolve any conflict that result from that merge

**Review by shargon — CHANGES_REQUESTED** [review]
You can now resolve the conflicts

**Comment by aboimpinto** [comment]
all the conflicts are now solved on the PR

**Review by shargon — APPROVED** [review]

**Pull request merged**
