### PR TITLE
Change Types Unit Tests to use FluentAssertions

### PR DESCRIPTION
**Pull request by BSathvik**
- Changed `UtDecimal`, `UtPool`, `UtFixed8`, `UtBigDecimal` and `AssertingThatFixed8` to use FluentAssertions.

### CODE REVIEW

**Review by aboimpinto — APPROVED** [review]

**Comment by shargon** [comment]
We had this discussion time ago, we need to define the rule for the UT, fluent or no?

**Comment by osmirnov** [comment]
@BSathvik Please rename unit test classes to be preffixed with Ut.

**Comment by BSathvik** [comment]
@osmirnov If you're referring to `AssertingThatFixed8`. Its not a Ut class itself. It is used in a Ut class. But if you think prefixing it with Ut is still a good idea then, I can do that.

**Comment by shargon** [comment]
Could you rebase? there are 62 changes, and some of this changes are mine (previous changes)

**Pull request merged**
