### PR TITLE
Travis-CI running tests inside docker container and deploy to official docker hub

### PR DESCRIPTION
**Pull request by nunojusto**
Solving issue #318 

- Travis-CI now builds and starts a SDK container and runs all coverage tests in it
- If all tests are successful, it builds the runtime image container
- In the end, publishes both SDK and runtime image containers to official CoZ neo-sharp docker hub

IMPORTANT NOTE:
Don't merge this PR without Travis-CI environment variables (for docker login and repo) being setup
Need @gubanotorious and @metachris to help on that

### CODE REVIEW

**Comment by nunojusto** [comment]
IMPORTANT NOTE:
Don't merge this PR without Travis-CI environment variables (for docker login and repo) being setup
Need @gubanotorious and @metachris to help on that

Variables to set:
REPO=cityofzion/neo-sharp
DOCKER_USER=username_for_cityofzion_hub
DOCKER_PASS=password_for_cityofzion_hub

**Comment by osmirnov** [comment]
@nunojusto please fix Travis build. Also, next time, please create a feature branch from your dev branch and make PR from that.

**Comment by nunojusto** [comment]
Hello, thanks for reply but Travis-CI will not be fixed without Env Variables to be set on the Travis dashboard.
That's why it's not building. $REPO is empty.
I need @gubanotorious and @metachris 

About the branch, ok, next time I'll do it like you say. No prob

**Comment by nunojusto** [comment]
@osmirnov, now it's all done. You can merge this, please.

**Pull request merged**
