### PR TITLE
Readonly serializer

### PR DESCRIPTION
**Pull request by shargon**
```csharp
public class ReadOnlyDummyClass
        {
            [BinaryProperty(0)]
            public readonly SetTest Test;

            public ReadOnlyDummyClass(SetTest test)
            {
                Test = test;
            }
        }
```

### CODE REVIEW

**Review by osmirnov — COMMENTED** [review]
I think the convention to have the same order for ctor params can be very limited

**Comment by osmirnov** [comment]
This is what I meant when requested the change:
```csharp
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace ReadOnlySerializer
{
    class Program
    {
        class SignedTransaction
        {
            // For serialization
            private SignedTransaction()
            {
            }

            // For runtime
            public SignedTransaction(uint index)
            {
                Index = index;
            }

            public uint Index { get; private set; }

        }

        class SignedBlock
        {
            // For serialization
            private SignedBlock()
            {
            }

            // For runtime
            public SignedBlock(uint index, IReadOnlyList<SignedTransaction> transactions)
            {
                Index = index;
                Transactions = transactions;
            }

            public uint Index { get; private set; }
            public IReadOnlyList<SignedTransaction> Transactions { get; private set; }
        }

        static void Main(string[] args)
        {
            var signedTransactions = new SignedTransaction[]
            {
                new SignedTransaction(1),
                new SignedTransaction(2),
                new SignedTransaction(3)
            };
            var signedBlock = new SignedBlock(1, signedTransactions);

            var memory = new MemoryStream();
            Serialize(memory, signedBlock);

            memory.Seek(0, SeekOrigin.Begin);
            var newSignedBlock = Deserialize(memory);

            Console.ReadKey();
        }

        private static void Serialize(Stream stream, SignedBlock instance)
        {
            var writer = new BinaryWriter(stream);

            writer.Write(instance.Index);
            writer.Write(instance.Transactions.Count);

            foreach (var transaction in instance.Transactions)
            {
                writer.Write(transaction.Index);
            }
        }

        private static SignedBlock Deserialize(Stream stream)
        {
            var instance = (SignedBlock)Activator.CreateInstance(typeof(SignedBlock), true);
            var reader = new BinaryReader(stream);
            var type = instance.GetType();

            var indexProp = type.GetProperty("Index");
            var index = reader.ReadUInt32();

            indexProp.SetValue(instance, index);

            var transactionsProp = type.GetProperty("Transactions");
            var transactionType = typeof(SignedTransaction);
            var transactionIndexProp = transactionType.GetProperty("Index");

            var transactionsCount = reader.ReadInt32();

            var transactions = Enumerable.Range(0, transactionsCount)
                .Select(_ =>
                {
                    var transaction = (SignedTransaction)Activator.CreateInstance(typeof(SignedTransaction), true);
                    var transactionIndex = reader.ReadUInt32();

                    transactionIndexProp.SetValue(transaction, transactionIndex);

                    return transaction;
                })
                .ToArray();

            transactionsProp.SetValue(instance, transactions);

            return instance;
        }
    }
}
```
@aboimpinto please check it as well we know we are on the same page.

**Comment by aboimpinto** [comment]
Yes ... we are at the same page!
the changes that I'm promoting are going in this direction ...

The deserialization is not yet implemented but for sure will use a similar procedure as this.

**Comment by shargon** [comment]
Ok! I only need to add IReadOnlyList and is possible

**Comment by shargon** [comment]
@osmirnov 
i think that in your sample, the constructor without parameters should be removed

```csharp
class SignedBlock
        {
            // For serialization
            public SignedBlock(uint index, IReadOnlyList<SignedTransaction> transactions)
            {
                Index = index;
                Transactions = transactions;
            }

            [BinaryProperty(0)]
            public uint Index { get; private set; }

            [BinaryProperty(1)]
            public IReadOnlyList<SignedTransaction> Transactions { get; private set; }
        }
```

**Comment by osmirnov** [comment]
Well, my example has a bit of simplification. In reality we would have:
```csharp
class SignedBlock
{
    // For runtime
    public SignedBlock(Block block, IReadOnlyList<SignedTransaction> transactions, UInt256 hash)
    {
        Version = block.Version;
        PreviousBlockHash = block.PreviousBlockHash;
        Index = block.Index;
        Hash = hash;
        Transactions = transactions;
    }

    public uint Version { get; private set; }
    public UInt256 PreviousBlockHash { get; private set; }
    public uint Index { get; private set; }
    public UInt256 Hash { get; private set; }    
    public IReadOnlyList<SignedTransaction> Transactions { get; private set; }    
}
```

**Comment by shargon** [comment]
`Hash` is not serialized, how could the serializer get this property?

**Comment by osmirnov** [comment]
Why do you think ```Hash``` is not serialized? We serialize and deserialize all public props in this class.

**Comment by shargon** [comment]
Currently, in neo the hash is not serialized

**Comment by shargon** [comment]
I merge it because your example is possible with this changes (adding the attributes), but are not compatible with neo.

**Pull request merged**
