### PR TITLE
Make RocksDbRepository testable.

### PR DESCRIPTION
**Pull request by aboimpinto**
* Fixing invalid references
* Replace byte[] it the IRepository with read Type (Uint256) more useful in the Application
* Extracting IRocksDbContext in order to make the RocksDbRepository testable.

tests will be added in the next PR

### CODE REVIEW

**Comment by osmirnov** [comment]
@shargon in #169 you changed the registration of dependencies for the persistence. Could you please contact @aboimpinto and decide what works better for all? I don't want to overwrite this in every PR 😟

**Review by gubanotorious — COMMENTED** [review]
I think this looks okay on a read to me. 

@osmirnov?

**Comment by osmirnov** [comment]
Yes, it looks good I only concern about PersistenceModule conflict I've asked guys to decide upon.

**Comment by gubanotorious** [comment]
Agreed.  I noticed that and assumed that would be resolved, the rest looked OK.

**Review by shargon — APPROVED** [review]

**Pull request merged**
